Vote spacing
nanocurrency/nano-node pull request #2763
Opened 2020-05-07 12:24 UTC by clemahieu

Currently there is no rate limiter on vote generation for a particular root and this can lead to increased, unnecessary vote traffic.

The nano::vote_reserver class was created to track the last time a vote was generated for a particular root.

In order to accurately and globally throttle votes, all vote generation was moved to vote_generator::vote and should not be done elsewhere.

nano::vote_generator processes two separate vote pipelines: live traffic and requests.

2020-05-08 23:08 UTC, SergiySW commented on nano/core_test/vote_generation.cpp
> +	// Start an election for send3, then publish send3_fork as welll
Typo "well"

2020-05-08 23:11 UTC, SergiySW commented on nano/node/blockprocessor.cpp
> -					node.votes_cache.remove (i->hash ());
Need to modify comment above

2020-11-19 19:43 UTC, wezrule submitted a review, later dismissed

2020-11-20 12:40 UTC, SergiySW approved these changes

2020-12-29 11:55 UTC, wezrule requested changes

2020-12-29 11:55 UTC, wezrule commented on nano/node/voting.hpp
> +	friend class vote_generator_vote_rapid_Test;
There are 2 new `vote_spacing` tests added but it doesn't match these. So it doesn't look like these friend declarations are necessary anymore (and also the nano namespace around the tests)

2021-01-11 18:56 UTC, wezrule submitted a review, later dismissed

2021-01-12 00:00 UTC, argakiig approved these changes

2021-01-12 00:05 UTC, merged