correct artifact for rocksdb and osx
nanocurrency/nano-node pull request #2928
Opened 2020-09-11 20:43 UTC by argakiig

2020-09-11 20:51 UTC, guilhermelawless approved these changes

2020-09-14 08:21 UTC, guilhermelawless requested changes
New version required for #2930

2020-09-14 21:19 UTC, wezrule approved these changes

2020-09-14 21:20 UTC, guilhermelawless approved these changes

2020-09-14 21:21 UTC, merged