Send only confirmed frontiers for bootstrap
nanocurrency/nano-node pull request #3047
Opened 2020-11-11 04:51 UTC by SergiySW

In frontier_req client/server & bulk_pull server

2020-11-16 21:09 UTC, wezrule submitted a review, later dismissed

2020-11-18 17:38 UTC, clemahieu submitted a review, later dismissed

2020-12-02 23:40 UTC, PlasmaPower commented
Could you add a flag to bypass this? I've been using the bootstrapping APIs to diagnose network issues, and this would significantly limit my capabilities.

2020-12-02 23:53 UTC, Srayman commented
Is bulk pull server used for lazy bootstraps also?  Wondering if this change really only needs to be made for when frontiers are requested for legacy bootstraps since that’s what causes nodes to ban each other if they send bad frontiers, but I don’t think the same happens for lazy bootstraps.  Would that solve the comment from @PlasmaPower to allow bulk pull to send any blocks but only send confirmed frontiers for legacy attempts?

That would maybe help with fork resolution also when a lazy attempt is made after seeing enough votes on the other fork?

2020-12-02 23:55 UTC, PlasmaPower commented
I think either of these changes (or maybe both?) make sense:
- If the bulk pull start is a hash, go ahead regardless of confirmation status
- If the header extensions contains a flag, ignore confirmation status

2021-01-07 20:47 UTC, SergiySW commented
@PlasmaPower Now frontier_req_server and bulk_pull_server can ignore confirmation status with header extension flag

2021-01-07 20:50 UTC, PlasmaPower commented
Thanks! I appreciate it.

2021-01-07 20:50 UTC, PlasmaPower commented
Thanks! I appreciate it.

2021-01-07 22:18 UTC, zhyatt reviewed
@PlasmaPower Disregard this previous method, didn't have the comments above on my side :)

2021-01-11 16:54 UTC, wezrule submitted a review, later dismissed

2021-01-11 18:35 UTC, clemahieu requested changes

2021-01-11 18:35 UTC, clemahieu commented on nano/node/bootstrap/bootstrap_attempt.cpp
>  	nano::pull_info pull (pull_a);
There doesn't seem to be a reason to copy this here.

2021-01-11 18:35 UTC, clemahieu commented on nano/node/bootstrap/bootstrap_server.cpp
> +					node->logger.try_log (boost::str (boost::format ("Received bulk pull for %1% down to %2%, maximum of %3% from %4%") % request->start.to_string () % request->end.to_string () % (request->count ?
These clauses are almost identical, can we just always log the remote endpoint?

2021-01-11 18:35 UTC, clemahieu commented on nano/node/bootstrap/bootstrap_bulk_pull.cpp
> +	send_unconfirmed_blocks = request->header.bootstrap_are_unconfirmed_blocks_present ();
Rather than being a member variable, I think this should be a function that returns request->header.bootstrap_are_unconfirmed_blocks_present (), then there's no risk of this value being incorrectly set.

2021-01-12 01:04 UTC, SergiySW commented on nano/node/bootstrap/bootstrap_attempt.cpp
>  	nano::pull_info pull (pull_a);
Updated, but probably there was some reason long ago (?)

2021-01-12 01:04 UTC, SergiySW commented on nano/node/bootstrap/bootstrap_bulk_pull.cpp
> +	send_unconfirmed_blocks = request->header.bootstrap_are_unconfirmed_blocks_present ();
Udpated

2021-01-12 01:04 UTC, SergiySW commented on nano/node/bootstrap/bootstrap_server.cpp
> +					node->logger.try_log (boost::str (boost::format ("Received bulk pull for %1% down to %2%, maximum of %3% from %4%") % request->start.to_string () % request->end.to_string () % (request->count ?
Udpated

2021-01-12 15:44 UTC, clemahieu approved these changes, later dismissed

2021-01-12 15:45 UTC, wezrule submitted a review, later dismissed

2021-02-02 15:04 UTC, wezrule submitted a review, later dismissed

2021-03-30 22:42 UTC, SergiySW commented
For v22 replaced with https://github.com/nanocurrency/nano-node/pull/3152

2021-03-30 22:42 UTC, closed without merging