Add [[nodiscard]] attribute to node::process method
nanocurrency/nano-node pull request #3505
Opened 2021-10-15 10:56 UTC by theohax

Compiling locally I did not see any build failures, but let's see the CI result first.

2021-10-15 11:18 UTC, clemahieu requested changes
Can we get the associated warning silenced by handling the return value. In tests we can do ASSERT_EQ to check for the correct process result.

2021-10-15 11:28 UTC, theohax commented
> Can we get the associated warning silenced by handling the return value. In tests we can do ASSERT_EQ to check for the correct process result.

Ohh that's why I didn't see it, I was expecting an error, but we're not compiling with -Werror, yeah...

I'll search manually for the usages and fix them.

2021-10-15 13:07 UTC, theohax commented
@clemahieu seems good now, can you have another look? thanks!

2021-10-16 04:43 UTC, clemahieu approved these changes

2021-10-16 04:44 UTC, merged