Add receive_hash option for the blocks_info RPC
nanocurrency/nano-node pull request #3702
Opened 2022-01-31 23:34 UTC by Exxenoz

Closes #3701

2022-02-03 13:51 UTC, Exxenoz commented
@dsiganos * Fixed clang format

2022-02-05 18:14 UTC, Exxenoz commented
Small consistency update: In case no receive block is found the full zero hash is now returned instead of just "0" (similar to the "successor" field).

2022-03-15 19:34 UTC, dsiganos commented on nano/node/json_handler.cpp
> +								nano::block_hash previous (node.ledger.latest (transaction, destination));
We do not want to return the latest block because that could be unconfirmed.
We want to stop returning unconfirmed blocks in general so any new functionality should default to returning confirmed data only by querying the confirmation height processor.

2022-03-15 19:34 UTC, dsiganos commented on nano/node/json_handler.cpp
> +									block_source = node.ledger.block_source (transaction, *previous_block);
Can we call this function in a pruned node?
It seems to assert that the previous block to the block given exists in the ledger.

2022-03-15 23:31 UTC, dsiganos commented
@Exxenoz I made some improvements. PLease review, if possible.

2022-03-16 16:33 UTC, Exxenoz commented
> @Exxenoz I made some improvements. PLease review, if possible.

Looks good to me. 👍

2022-03-28 11:31 UTC, clemahieu submitted a review, later dismissed

2022-03-28 13:00 UTC, thsfs requested changes

2022-03-28 13:00 UTC, thsfs commented on nano/node/node.cpp
> +/** Given the block hash of a send block, find the associated receive block that receives that send.
IMO, this function should be packed into the ledger.cpp file, or in another more specific file, if there is a better one. This is more related to the ledger logic and the node is a more general class.

2022-03-28 16:25 UTC, dsiganos commented on nano/node/node.cpp
> +/** Given the block hash of a send block, find the associated receive block that receives that send.
I agree. But I do not yet understand how the database classes are structured and I don't know how to do that.
So I have taken the easy and slightly less accurate route of implementing in the node class.
We can work on this together to improve it, if you like.

2022-03-28 17:27 UTC, thsfs commented on nano/node/node.cpp
> +/** Given the block hash of a send block, find the associated receive block that receives that send.
My preference is to send the function to `json_handler.cpp` as it isn't used anywhere else, but as you @dsiganos foresee other usages, so let's keep the function in the ledger class.

2022-03-28 17:32 UTC, thsfs approved these changes, later dismissed

2022-03-28 20:07 UTC, dsiganos commented
This PR couldn;t merged because it was conflicting.
Merging would be too messy because this Pr has been alive for too long.
So I squashed and rebased and then resolved the conflicts.
Please recheck.

2022-03-28 23:45 UTC, dsiganos approved these changes

2022-03-28 23:46 UTC, merged