Updating to use c++20
nanocurrency/nano-node pull request #4017
Opened 2022-12-02 15:52 UTC by clemahieu

Fixing various type ambiguities flagged in c++20 mode.

2022-12-02 16:09 UTC, dsiganos requested changes

2022-12-02 16:09 UTC, dsiganos commented on nano/lib/numbers.cpp
> +	return true;
This can't be right.

2022-12-03 14:45 UTC, dsiganos submitted a review, later dismissed

2022-12-07 11:41 UTC, clemahieu commented
Looks like boost will need a new version.

Boost asio coroutine support: https://www.boost.org/users/history/version_1_74_0.html
c++20 compiler testing: https://www.boost.org/users/history/version_1_77_0.html

2022-12-30 07:05 UTC, guilhermelawless commented
https://github.com/nanocurrency/nano-node/blob/9bb89ab3232eb603911ae1125a78921ec2d4f591/nano/node/distributed_work_factory.cpp#L57

2023-01-16 10:28 UTC, merged

2023-03-01 17:40 UTC, thsfs commented
This change requires updating the documentation website, switching the compiler version from C++17 to C++20.