Convert boost::filesystem references to std::filesystem
nanocurrency/nano-node pull request #4183
Opened 2023-03-15 09:38 UTC by mariomoliner

associated issue #4057

2023-03-15 11:19 UTC, clemahieu requested changes
Also needs a formatting run ci/clang-format-do.sh

2023-03-15 11:19 UTC, clemahieu commented on nano/nano_rpc/CMakeLists.txt
> +  std::filesystem
This line should be removed.

2023-03-15 11:19 UTC, clemahieu commented on nano/core_test/common.hpp
> +#pragma once
It looks like some other files got mixed in.

2023-10-19 10:42 UTC, qwahzi commented
Closed by #4057 and #4315

2023-10-19 10:42 UTC, closed without merging